version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - pr-priority
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    groups:
      update-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 1